const plugin = require("tailwindcss/plugin");

/** @type {import('tailwindcss').Config} */

module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./lib/opal/**/*.{js,jsx,ts,tsx}"],
  theme: {
    container: {
      center: true,
    },
    transparent: "transparent",
    current: "currentColor",
    extend: {
      lineClamp: {
        7: "7",
        8: "8",
        9: "9",
        10: "10",
      },
      transitionProperty: {
        spacing: "margin, padding",
      },
      keyframes: {
        "subtle-pulse": {
          "0%, 100%": { opacity: 0.9 },
          "50%": { opacity: 0.5 },
        },
        pulse: {
          "0%, 100%": { opacity: 0.9 },
          "50%": { opacity: 0.4 },
        },
        "fade-in-scale": {
          "0%": { opacity: "0", transform: "scale(0.95)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "fade-out-scale": {
          "0%": { opacity: "1", transform: "scale(1)" },
          "100%": { opacity: "0", transform: "scale(0.95)" },
        },
        "collapsible-down": {
          from: { height: "0" },
          to: { height: "var(--radix-collapsible-content-height)" },
        },
        "collapsible-up": {
          from: { height: "var(--radix-collapsible-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "fade-in-up": "fadeInUp 0.5s ease-out",
        "subtle-pulse": "subtle-pulse 2s ease-in-out infinite",
        pulse: "pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in-scale": "fade-in-scale 0.2s ease-out forwards",
        "fade-out-scale": "fade-out-scale 0.2s ease-in forwards",
        "collapsible-down": "collapsible-down 0.2s ease-out",
        "collapsible-up": "collapsible-up 0.2s ease-out",
      },
      gradientColorStops: {
        "neutral-10": "var(--neutral-10) 5%",
      },
      screens: {
        sm: "724px",
        md: "912px",
        lg: "1232px",
        "2xl": "1420px",
        "3xl": "1700px",
        "4xl": "2000px",
        mobile: { max: "724px" },
        tall: { raw: "(min-height: 800px)" },
        short: { raw: "(max-height: 799px)" },
        "very-short": { raw: "(max-height: 600px)" },
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "sans-serif"],
        hanken: ["Hanken Grotesk", "sans-serif"],
      },
      width: {
        "message-xs": "450px",
        "message-sm": "550px",
        "message-default": "740px",
        "searchbar-xs": "560px",
        "searchbar-sm": "660px",
        searchbar: "850px",
        "document-sidebar": "800px",
        "document-sidebar-large": "1000px",
        "searchbar-max": "60px",
      },
      maxWidth: {
        "document-sidebar": "1000px",
        "message-max": "850px",
        "content-max": "725px",
        "searchbar-max": "800px",
      },
      colors: {
        // New and updated Figma stylings
        "text-05": "var(--text-05)",
        "text-04": "var(--text-04)",
        "text-03": "var(--text-03)",
        "text-02": "var(--text-02)",
        "text-01": "var(--text-01)",
        "text-inverted-01": "var(--text-inverted-01)",
        "text-inverted-02": "var(--text-inverted-02)",
        "text-inverted-03": "var(--text-inverted-03)",
        "text-inverted-04": "var(--text-inverted-04)",
        "text-inverted-05": "var(--text-inverted-05)",
        "text-light-03": "var(--text-light-03)",
        "text-light-05": "var(--text-light-05)",
        "text-dark-03": "var(--text-dark-03)",
        "text-dark-05": "var(--text-dark-05)",
        "background-neutral-00": "var(--background-neutral-00)",
        "background-neutral-01": "var(--background-neutral-01)",
        "background-neutral-02": "var(--background-neutral-02)",
        "background-neutral-03": "var(--background-neutral-03)",
        "background-neutral-04": "var(--background-neutral-04)",
        "background-neutral-light-00": "var(--background-neutral-light-00)",
        "background-neutral-light-03": "var(--background-neutral-light-03)",
        "background-neutral-dark-03": "var(--background-neutral-dark-03)",
        "background-neutral-inverted-04":
          "var(--background-neutral-inverted-04)",
        "background-neutral-inverted-03":
          "var(--background-neutral-inverted-03)",
        "background-neutral-inverted-02":
          "var(--background-neutral-inverted-02)",
        "background-neutral-inverted-01":
          "var(--background-neutral-inverted-01)",
        "background-neutral-inverted-00":
          "var(--background-neutral-inverted-00)",
        "background-tint-00": "var(--background-tint-00)",
        "background-tint-01": "var(--background-tint-01)",
        "background-tint-02": "var(--background-tint-02)",
        "background-tint-03": "var(--background-tint-03)",
        "background-tint-04": "var(--background-tint-04)",
        "background-tint-inverted-04": "var(--background-tint-inverted-04)",
        "background-tint-inverted-03": "var(--background-tint-inverted-03)",
        "background-tint-inverted-02": "var(--background-tint-inverted-02)",
        "background-tint-inverted-01": "var(--background-tint-inverted-01)",
        "background-tint-inverted-00": "var(--background-tint-inverted-00)",
        "border-01": "var(--border-01)",
        "border-02": "var(--border-02)",
        "border-03": "var(--border-03)",
        "border-04": "var(--border-04)",
        "border-05": "var(--border-05)",
        "border-inverted-05": "var(--border-inverted-05)",
        "border-inverted-04": "var(--border-inverted-04)",
        "border-inverted-03": "var(--border-inverted-03)",
        "border-inverted-02": "var(--border-inverted-02)",
        "border-inverted-01": "var(--border-inverted-01)",
        "action-link-06": "var(--action-link-06)",
        "action-link-05": "var(--action-link-05)",
        "action-link-04": "var(--action-link-04)",
        "action-link-03": "var(--action-link-03)",
        "action-link-02": "var(--action-link-02)",
        "action-link-01": "var(--action-link-01)",
        "action-link-00": "var(--action-link-00)",
        "action-danger-06": "var(--action-danger-06)",
        "action-danger-05": "var(--action-danger-05)",
        "action-danger-04": "var(--action-danger-04)",
        "action-danger-03": "var(--action-danger-03)",
        "action-danger-02": "var(--action-danger-02)",
        "action-danger-01": "var(--action-danger-01)",
        "action-text-link-05": "var(--action-text-link-05)",
        "action-text-danger-05": "var(--action-text-danger-05)",
        "highlight-match": "var(--highlight-match)",
        "highlight-selection": "var(--highlight-selection)",
        "highlight-active": "var(--highlight-active)",
        "highlight-accent": "var(--highlight-accent)",
        "theme-primary-06": "var(--theme-primary-06)",
        "theme-primary-05": "var(--theme-primary-05)",
        "theme-primary-04": "var(--theme-primary-04)",
        "theme-gradient-05": "var(--theme-gradient-05)",
        "theme-gradient-00": "var(--theme-gradient-00)",
        "theme-red-05": "var(--theme-red-05)",
        "theme-red-04": "var(--theme-red-04)",
        "theme-red-02": "var(--theme-red-02)",
        "theme-red-01": "var(--theme-red-01)",
        "theme-orange-05": "var(--theme-orange-05)",
        "theme-orange-04": "var(--theme-orange-04)",
        "theme-orange-02": "var(--theme-orange-02)",
        "theme-orange-01": "var(--theme-orange-01)",
        "theme-amber-05": "var(--theme-amber-05)",
        "theme-amber-04": "var(--theme-amber-04)",
        "theme-amber-02": "var(--theme-amber-02)",
        "theme-amber-01": "var(--theme-amber-01)",
        "theme-yellow-05": "var(--theme-yellow-05)",
        "theme-yellow-02": "var(--theme-yellow-02)",
        "theme-yellow-01": "var(--theme-yellow-01)",
        "theme-green-05": "var(--theme-green-05)",
        "theme-green-02": "var(--theme-green-02)",
        "theme-green-01": "var(--theme-green-01)",
        "theme-lime-05": "var(--theme-lime-05)",
        "theme-lime-02": "var(--theme-lime-02)",
        "theme-lime-01": "var(--theme-lime-01)",
        "theme-cyan-05": "var(--theme-cyan-05)",
        "theme-cyan-02": "var(--theme-cyan-02)",
        "theme-cyan-01": "var(--theme-cyan-01)",
        "theme-sky-05": "var(--theme-sky-05)",
        "theme-sky-02": "var(--theme-sky-02)",
        "theme-sky-01": "var(--theme-sky-01)",
        "theme-blue-05": "var(--theme-blue-05)",
        "theme-blue-02": "var(--theme-blue-02)",
        "theme-blue-01": "var(--theme-blue-01)",
        "theme-purple-05": "var(--theme-purple-05)",
        "theme-purple-02": "var(--theme-purple-02)",
        "theme-purple-01": "var(--theme-purple-01)",
        "theme-magenta-05": "var(--theme-magenta-05)",
        "theme-magenta-02": "var(--theme-magenta-02)",
        "theme-magenta-01": "var(--theme-magenta-01)",
        "onyx-ink-100": "var(--onyx-ink-100)",
        "onyx-ink-95": "var(--onyx-ink-95)",
        "onyx-ink-90": "var(--onyx-ink-90)",
        "onyx-chrome-20": "var(--onyx-chrome-20)",
        "onyx-chrome-10": "var(--onyx-chrome-10)",
        "onyx-chrome-00": "var(--onyx-chrome-00)",
        "tint-98": "var(--tint-98)",
        "tint-95": "var(--tint-95)",
        "tint-90": "var(--tint-90)",
        "tint-85": "var(--tint-85)",
        "tint-80": "var(--tint-80)",
        "tint-60": "var(--tint-60)",
        "tint-50": "var(--tint-50)",
        "tint-40": "var(--tint-40)",
        "tint-20": "var(--tint-20)",
        "tint-10": "var(--tint-10)",
        "tint-05": "var(--tint-05)",
        "tint-02": "var(--tint-02)",
        "shadow-01": "var(--shadow-01)",
        "shadow-02": "var(--shadow-02)",
        "shadow-03": "var(--shadow-03)",
        "mask-01": "var(--mask-01)",
        "mask-02": "var(--mask-02)",
        "mask-03": "var(--mask-03)",
        "status-info-05": "var(--status-info-05)",
        "status-info-02": "var(--status-info-02)",
        "status-info-01": "var(--status-info-01)",
        "status-info-00": "var(--status-info-00)",
        "status-success-05": "var(--status-success-05)",
        "status-success-02": "var(--status-success-02)",
        "status-success-01": "var(--status-success-01)",
        "status-success-00": "var(--status-success-00)",
        "status-warning-05": "var(--status-warning-05)",
        "status-warning-02": "var(--status-warning-02)",
        "status-warning-01": "var(--status-warning-01)",
        "status-warning-00": "var(--status-warning-00)",
        "status-error-05": "var(--status-error-05)",
        "status-error-02": "var(--status-error-02)",
        "status-error-01": "var(--status-error-01)",
        "status-error-00": "var(--status-error-00)",
        "status-text-success-05": "var(--status-text-success-05)",
        "status-text-info-05": "var(--status-text-info-05)",
        "status-text-warning-05": "var(--status-text-warning-05)",
        "status-text-error-05": "var(--status-text-error-05)",

        "code-code": "var(--code-code)",
        "code-comment": "var(--code-comment)",
        "code-keyword": "var(--code-keyword)",
        "code-string": "var(--code-string)",
        "code-number": "var(--code-number)",
        "code-definition": "var(--code-definition)",
        "background-code-01": "var(--background-code-01)",

        // Shimmer colors for loading animations
        "shimmer-base": "var(--shimmer-base)",
        "shimmer-highlight": "var(--shimmer-highlight)",

        // Tailwind defaults
        background: "var(--background-tint-01)",
        foreground: "var(--background-tint-inverted-01)",
        border: "var(--border-01)",
        text: "var(--text-04)",
      },
      borderRadius: {
        "02": "var(--border-radius-02)",
        "04": "var(--border-radius-04)",
        "08": "var(--border-radius-08)",
        12: "var(--border-radius-12)",
        16: "var(--border-radius-16)",
        full: "var(--border-radius-full)",
      },
      fontSize: {
        "2xs": "0.625rem",
        "code-sm": "small",
      },
      fontWeight: {
        description: "375",
        "token-bold": "bold",
      },
      fontStyle: {
        "token-italic": "italic",
      },
      backdropBlur: {
        "01": "var(--backdrop-blur-01)",
        "02": "var(--backdrop-blur-02)",
        "03": "var(--backdrop-blur-03)",
      },
      calendar: {
        // Light mode
        "bg-selected": "var(--calendar-bg-selected)",
        "bg-outside-selected": "var(--calendar-bg-outside-selected)",
        "text-muted": "var(--calendar-text-muted)",
        "text-selected": "var(--calendar-text-selected)",
        "range-start": "var(--calendar-range-start)",
        "range-middle": "var(--calendar-range-middle)",
        "range-end": "var(--calendar-range-end)",
        "text-in-range": "var(--calendar-text-in-range)",

        // Dark mode
        "bg-selected-dark": "var(--calendar-bg-selected-dark)",
        "bg-outside-selected-dark": "var(--calendar-bg-outside-selected-dark)",
        "text-muted-dark": "var(--calendar-text-muted-dark)",
        "text-selected-dark": "var(--calendar-text-selected-dark)",
        "range-start-dark": "var(--calendar-range-start-dark)",
        "range-middle-dark": "var(--calendar-range-middle-dark)",
        "range-end-dark": "var(--calendar-range-end-dark)",
        "text-in-range-dark": "var(--calendar-text-in-range-dark)",

        // Hover effects
        "hover-bg": "var(--calendar-hover-bg)",
        "hover-bg-dark": "var(--calendar-hover-bg-dark)",
        "hover-text": "var(--calendar-hover-text)",
        "hover-text-dark": "var(--calendar-hover-text-dark)",

        // Today's date
        "today-bg": "var(--calendar-today-bg)",
        "today-bg-dark": "var(--calendar-today-bg-dark)",
        "today-text": "var(--calendar-today-text)",
        "today-text-dark": "var(--calendar-today-text-dark)",
      },
    },
  },
  safelist: [
    {
      pattern:
        /^(bg-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
      variants: ["hover", "ui-selected"],
    },
    {
      pattern:
        /^(text-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
      variants: ["hover", "ui-selected"],
    },
    {
      pattern:
        /^(border-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
      variants: ["hover", "ui-selected"],
    },
    {
      pattern:
        /^(ring-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
    },
    {
      pattern:
        /^(stroke-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
    },
    {
      pattern:
        /^(fill-(?:slate|gray|zinc|neutral|stone|red|orange|amber|yellow|lime|green|emerald|teal|cyan|sky|blue|indigo|violet|purple|fuchsia|pink|rose)-(?:50|100|200|300|400|500|600|700|800|900|950))$/,
    },
  ],
  // Note: @tailwindcss/container-queries plugin is not needed here.
  // Container queries (@container, cqw units) are native in Tailwind v4+.
  // After upgrading to Tailwind 4, this comment can be removed.
  plugins: [
    require("@tailwindcss/typography"),
    require("@headlessui/tailwindcss"),
    require("tailwindcss-animate"),
    require("@tailwindcss/container-queries"),
    plugin(({ addVariant }) => {
      addVariant("focus-within-nonactive", "&:focus-within:not(:active)");
    }),
    plugin(({ addUtilities }) => {
      addUtilities({
        ".break-anywhere": {
          "overflow-wrap": "anywhere",
        },
      });
    }),
  ],
};
