{{- if and .Values.vectorDB.enabled (gt (int .Values.celery_worker_light.replicaCount) 0) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "onyx.fullname" . }}-celery-worker-light
  labels:
    {{- include "onyx.labels" . | nindent 4 }}
    {{- with .Values.celery_worker_light.deploymentLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.celery_worker_light.autoscaling.enabled }}
  replicas: {{ .Values.celery_worker_light.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "onyx.selectorLabels" . | nindent 6 }}
      {{- if .Values.celery_worker_light.deploymentLabels }}
      {{- toYaml .Values.celery_worker_light.deploymentLabels | nindent 6 }}
      {{- end }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.celery_worker_light.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "onyx.labels" . | nindent 8 }}
        {{- with .Values.celery_worker_light.deploymentLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.celery_worker_light.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "onyx.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.celery_shared.podSecurityContext | nindent 8 }}
      {{- with .Values.celery_worker_light.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celery_worker_light.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.celery_worker_light.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: celery-worker-light
          securityContext:
            {{- toYaml .Values.celery_shared.securityContext | nindent 12 }}
          image: "{{ .Values.celery_shared.image.repository }}:{{ .Values.celery_shared.image.tag | default .Values.global.version }}"
          imagePullPolicy: {{ .Values.global.pullPolicy }}
          command:
            [
              "celery",
              "-A",
              "onyx.background.celery.versioned_apps.light",
              "worker",
              {{ printf "--loglevel=%s" .Values.celery_worker_light.logLevel | quote }},
              "--hostname=light@%n",
              "-Q",
              "vespa_metadata_sync,connector_deletion,doc_permissions_upsert,checkpoint_cleanup,index_attempt_cleanup,opensearch_migration",
            ]
          ports:
            - name: metrics
              containerPort: 9095
              protocol: TCP
          resources:
            {{- toYaml .Values.celery_worker_light.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.envConfigMapName }}
          env:
            {{- include "onyx.envSecrets" . | nindent 12}}
          {{- with .Values.celery_worker_light.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          startupProbe:
            {{ .Values.celery_shared.startupProbe | toYaml | nindent 12}}
          readinessProbe:
            {{ .Values.celery_shared.readinessProbe | toYaml | nindent 12}}
            exec:
              command:
                - /bin/bash
                - -c
                - >
                    python onyx/background/celery/celery_k8s_probe.py
                    --probe readiness
                    --filename /tmp/onyx_k8s_light_readiness.txt
          livenessProbe:
            {{ .Values.celery_shared.livenessProbe | toYaml | nindent 12}}
            exec:
              command:
                - /bin/bash
                - -c
                - >
                    python onyx/background/celery/celery_k8s_probe.py
                    --probe liveness
                    --filename /tmp/onyx_k8s_light_liveness.txt
      {{- with .Values.celery_worker_light.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
