{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "onyx.fullname" . }}-ingress-api
  annotations:
    {{- if not .Values.ingress.className }}
    kubernetes.io/ingress.class: nginx
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "{{ .Values.nginx.timeouts.read }}"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "{{ .Values.nginx.timeouts.send }}"
    nginx.ingress.kubernetes.io/proxy-body-size: "5G"
    cert-manager.io/cluster-issuer: {{ include "onyx.fullname" . }}-letsencrypt
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.api.host }}
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "onyx.fullname" . }}-api-service
                port:
                  number: {{ .Values.api.service.servicePort }}
  tls:
    - hosts:
        - {{ .Values.ingress.api.host }}
      secretName: {{ include "onyx.fullname" . }}-ingress-api-tls
{{- end }}