name: Nightly Tag Push

on:
  schedule:
    - cron: "0 10 * * *" # Runs every day at 2 AM PST / 3 AM PDT / 10 AM UTC
  workflow_dispatch:

permissions:
  contents: write # Allows pushing tags to the repository

jobs:
  create-and-push-tag:
    runs-on: ubuntu-slim
    environment: ci-protected
    timeout-minutes: 45

    steps:
      # actions using GITHUB_TOKEN cannot trigger another workflow, but we do want this to trigger docker pushes
      # see https://github.com/orgs/community/discussions/27028#discussioncomment-3254367 for the workaround we
      # implement here which needs an actual user's deploy key
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          ssh-key: "${{ secrets.DEPLOY_KEY }}"
          persist-credentials: true

      - name: Set up Git user
        run: |
          git config user.name "Onyx Bot [bot]"
          git config user.email "onyx-bot[bot]@onyx.app"

      - name: Check for existing nightly tag
        id: check_tag
        run: |
          if git tag --points-at HEAD --list "nightly-latest*" | grep -q .; then
            echo "A tag starting with 'nightly-latest' already exists on HEAD."
            echo "tag_exists=true" >> $GITHUB_OUTPUT
          else
            echo "No tag starting with 'nightly-latest' exists on HEAD."
            echo "tag_exists=false" >> $GITHUB_OUTPUT
          fi

      # don't tag again if HEAD already has a nightly-latest tag on it
      - name: Create Nightly Tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        env:
          DATE: ${{ github.run_id }}
        run: |
          TAG_NAME="nightly-latest-$(date +'%Y%m%d')"
          echo "Creating tag: $TAG_NAME"
          git tag $TAG_NAME

      - name: Push Tag
        if: steps.check_tag.outputs.tag_exists == 'false'
        run: |
          TAG_NAME="nightly-latest-$(date +'%Y%m%d')"
          git push origin $TAG_NAME

      - name: Send Slack notification
        if: failure()
        uses: ./.github/actions/slack-notify
        with:
          webhook-url: ${{ secrets.MONITOR_DEPLOYMENTS_WEBHOOK }}
          title: "🚨 Nightly Tag Push Failed"
          ref-name: ${{ github.ref_name }}
          failed-jobs: "create-and-push-tag"
