"""Drop all SSO / OIDC schema for the no-SSO delivery branch.

``feature/no-sso`` is shipped to closed deployments where the customer has
either a different SSO or none at all. The application layer has already
stripped every register / OIDC / sso-key entry point; this migration
removes the schema artefacts so the DB no longer carries dead tables /
columns the operator can stumble into.

Schema dropped:
- ``external_identities`` table (OIDC subject ↔ user binding)
- ``users.auth_provider_id`` column + FK
- ``auth_providers`` table
- ``users.local_password_disabled`` column (only useful when SSO existed)

Order matters: child rows / FK columns come before their parent table,
otherwise PostgreSQL refuses the drop.

downgrade() re-creates the **schema shape** so an alembic round-trip on
a fresh DB still works, but does NOT restore data — anyone needing the
old SSO data must reload from a backup.

Revision ID: 0035
Revises: 0034
Create Date: 2026-05-16
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


revision: str = "0035"
down_revision: Union[str, None] = "0034"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    # 1) external_identities → has FK to both users and auth_providers,
    # must drop before either of those.
    if "external_identities" in tables:
        op.drop_table("external_identities")

    # 2) users.auth_provider_id FK → drop column before its parent table.
    user_cols = {c["name"] for c in inspector.get_columns("users")}
    if "auth_provider_id" in user_cols:
        with op.batch_alter_table("users") as batch:
            # FK name is autogenerated by SQLAlchemy from the column name;
            # batch_alter_table figures it out. Belt-and-braces with the
            # column-drop in case FK was named explicitly.
            batch.drop_column("auth_provider_id")

    if "local_password_disabled" in user_cols:
        with op.batch_alter_table("users") as batch:
            batch.drop_column("local_password_disabled")

    # 3) auth_providers itself — last, because (1) and (2) FK'd into it.
    if "auth_providers" in tables:
        op.drop_table("auth_providers")


def downgrade() -> None:
    """Re-create the schema shape so alembic stays reversible.

    Restores empty tables / nullable columns. Does NOT restore data.
    """
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())
    user_cols = {c["name"] for c in inspector.get_columns("users")}

    if "auth_providers" not in tables:
        op.create_table(
            "auth_providers",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("name", sa.String(100), nullable=False),
            sa.Column("provider_type", sa.String(50), nullable=False),
            sa.Column("is_active", sa.Boolean(), nullable=False, server_default="true"),
            sa.Column("config", sa.JSON(), nullable=True),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text("now()"),
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("name"),
        )

    if "local_password_disabled" not in user_cols:
        with op.batch_alter_table("users") as batch:
            batch.add_column(
                sa.Column(
                    "local_password_disabled",
                    sa.Boolean(),
                    nullable=False,
                    server_default="false",
                )
            )

    if "auth_provider_id" not in user_cols:
        with op.batch_alter_table("users") as batch:
            batch.add_column(sa.Column("auth_provider_id", sa.Integer(), nullable=True))
            batch.create_foreign_key(
                "fk_users_auth_provider_id",
                "auth_providers",
                ["auth_provider_id"],
                ["id"],
                ondelete="SET NULL",
            )

    if "external_identities" not in tables:
        op.create_table(
            "external_identities",
            sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
            sa.Column("user_id", sa.Integer(), nullable=False),
            sa.Column("provider_id", sa.Integer(), nullable=False),
            sa.Column("external_id", sa.String(500), nullable=False),
            sa.Column(
                "created_at",
                sa.DateTime(timezone=True),
                nullable=False,
                server_default=sa.text("now()"),
            ),
            sa.ForeignKeyConstraint(
                ["provider_id"], ["auth_providers.id"], ondelete="CASCADE"
            ),
            sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint(
                "provider_id", "external_id", name="uq_external_identities_provider_external"
            ),
        )
