"""anila_agent.core — agent 組裝、執行、事件、hooks、tool context 的核心模組。"""

from __future__ import annotations

from anila_agent.core.agent_tool import (
    DEFAULT_SUBAGENT_TIMEOUT_SECONDS,
    AgentTool,
    PrefixStrategy,
    SubAgentRunner,
    get_agent_tool_spec,
    make_agent_tool,
    register_agent_as_tool,
)
from anila_agent.core.concurrency import (
    ToolCall,
    ToolInvoker,
    ToolResult,
    partition_tool_calls,
    run_tool_calls,
)
from anila_agent.core.cost_tracker import (
    DEFAULT_MODEL_PRICINGS,
    SPAN_ATTR_COMPLETION_TOKENS,
    SPAN_ATTR_COST_USD,
    SPAN_ATTR_MODEL,
    SPAN_ATTR_PROMPT_TOKENS,
    CostTracker,
    ModelPricing,
    PricingRegistry,
    inject_span_attributes,
)
from anila_agent.core.context import (
    AnilaToolContext,
    FileStateCache,
    FileStateEntry,
    WorkspaceEscapeError,
)
from anila_agent.core.coordinator import (
    CoordinatorMessage,
    CoordinatorNotification,
    format_coordinator_messages,
    parse_coordinator_messages,
)
from anila_agent.core.guardrails import (
    GuardrailResult,
    GuardrailTripwireTriggered,
    InputGuardrail,
    InputGuardrailProtocol,
    OutputGuardrail,
    OutputGuardrailProtocol,
    input_guardrail,
    output_guardrail,
)
from anila_agent.core.hook_context import (
    AnyHookCtx,
    HookContext,
    OperationContext,
    SessionContext,
    TurnContext,
)
from anila_agent.core.hook_flavors import (
    CommandHook,
    HookABC,
    HookFlavor,
    HttpHook,
    PromptHook,
    PythonHook,
)
from anila_agent.core.hook_taxonomy import (
    DecideHook,
    Decision,
    DecisionVerdict,
    HookExecutor,
    InspectHook,
    PipelineResult,
    TransformHook,
)
from anila_agent.core.permission_grammar import (
    EffectStr,
    PermissionRule,
    PermissionRuleSyntaxError,
    load_policy_engine_from_yaml,
    parse_permission_rule,
    parse_permission_rules,
    policy_rule_from_yaml_item,
)
from anila_agent.core.prompt_cache import (
    DEFAULT_PREFIX_MESSAGE_COUNT,
    FORK_BOILERPLATE_TAG,
    FORK_DIRECTIVE_PREFIX,
    SHARE_INSTRUCTION_PREFIX,
    Message,
    PrefixStrategyName,
    SubagentPrefix,
    build_fork_directive_message,
    build_share_directive_message,
    build_subagent_prefix,
    compute_prefix_hash,
    is_in_fork_child,
)
from anila_agent.core.run_state import (
    HITLController,
    JsonFileStateStore,
    PauseReason,
    RunState,
    RunStatus,
    pause_streaming_if_needed,
)
from anila_agent.core.task_manager import (
    DEFAULT_TASK_TIMEOUT_SECONDS,
    OnCompleteCallback,
    Task,
    TaskManager,
    TaskState,
)
from anila_agent.core.stop_hook import (
    KeywordStopHook,
    MaxIterationsStopHook,
    OutputLengthStopHook,
    StopHook,
    StopHookCallable,
    StopHookDecision,
    StopHookEntry,
    fire_stop_hook_chain,
)
from anila_agent.core.streaming import (
    AgentUpdatedStreamEvent,
    AnilaStreamRunner,
    RawResponseEvent,
    RunItemStreamEvent,
    RunItemType,
    StreamChunk,
    StreamEvent,
)
from anila_agent.core.policy import (
    PolicyDecision,
    PolicyEffect,
    PolicyEngine,
    PolicyRule,
    allow_all_except,
    apply_policy_to_system_context,
    deny_all,
    policy_to_tool_input_guardrail,
    read_only,
    workspace_only,
)
from anila_agent.core.token_budget import (
    DEFAULT_PTL_PATTERNS,
    BudgetExceeded,
    BudgetTracker,
    ContinuationStrategy,
    HardCallback,
    PTLRetry,
    SoftCallback,
    TruncateCallback,
    with_budget,
)

__all__ = [
    # P0-8 agent tool
    "AgentTool",
    "DEFAULT_SUBAGENT_TIMEOUT_SECONDS",
    "PrefixStrategy",
    "SubAgentRunner",
    "get_agent_tool_spec",
    "make_agent_tool",
    "register_agent_as_tool",
    # P0-3 context
    "AnilaToolContext",
    "FileStateCache",
    "FileStateEntry",
    "WorkspaceEscapeError",
    # P1-3 hook context 三層 scope
    "AnyHookCtx",
    "HookContext",
    "OperationContext",
    "SessionContext",
    "TurnContext",
    # P1-2 concurrency partition
    "ToolCall",
    "ToolInvoker",
    "ToolResult",
    "partition_tool_calls",
    "run_tool_calls",
    # P1-15 cost tracker + USD pricing
    "CostTracker",
    "DEFAULT_MODEL_PRICINGS",
    "ModelPricing",
    "PricingRegistry",
    "SPAN_ATTR_COMPLETION_TOKENS",
    "SPAN_ATTR_COST_USD",
    "SPAN_ATTR_MODEL",
    "SPAN_ATTR_PROMPT_TOKENS",
    "inject_span_attributes",
    # P0-4 hook flavors
    "CommandHook",
    "HookABC",
    "HookFlavor",
    "HttpHook",
    "PromptHook",
    "PythonHook",
    # P0-5 hook taxonomy
    "DecideHook",
    "Decision",
    "DecisionVerdict",
    "HookExecutor",
    "InspectHook",
    "PipelineResult",
    "TransformHook",
    # P0-6 guardrails
    "GuardrailResult",
    "GuardrailTripwireTriggered",
    "InputGuardrail",
    "InputGuardrailProtocol",
    "OutputGuardrail",
    "OutputGuardrailProtocol",
    "input_guardrail",
    "output_guardrail",
    # P0-7 policy DSL + P1-19 disable vs deny prompt filter
    "PolicyDecision",
    "PolicyEffect",
    "PolicyEngine",
    "PolicyRule",
    "allow_all_except",
    "apply_policy_to_system_context",
    "deny_all",
    "policy_to_tool_input_guardrail",
    "read_only",
    "workspace_only",
    # P1-9 token budget continuation
    "DEFAULT_PTL_PATTERNS",
    "BudgetExceeded",
    "BudgetTracker",
    "ContinuationStrategy",
    "HardCallback",
    "PTLRetry",
    "SoftCallback",
    "TruncateCallback",
    "with_budget",
    # P1-7 streaming
    "AgentUpdatedStreamEvent",
    "AnilaStreamRunner",
    "RawResponseEvent",
    "RunItemStreamEvent",
    "RunItemType",
    "StreamChunk",
    "StreamEvent",
    # P1-14 stop hook prevent-continuation
    "KeywordStopHook",
    "MaxIterationsStopHook",
    "OutputLengthStopHook",
    "StopHook",
    "StopHookCallable",
    "StopHookDecision",
    "StopHookEntry",
    "fire_stop_hook_chain",
    # P1-16 permission rule mini DSL
    "EffectStr",
    "PermissionRule",
    "PermissionRuleSyntaxError",
    "load_policy_engine_from_yaml",
    "parse_permission_rule",
    "parse_permission_rules",
    "policy_rule_from_yaml_item",
    # P1-13 coordinatorMode XML notification
    "CoordinatorMessage",
    "CoordinatorNotification",
    "format_coordinator_messages",
    "parse_coordinator_messages",
    # P1-1 forkSubagent byte-identical prefix
    "DEFAULT_PREFIX_MESSAGE_COUNT",
    "FORK_BOILERPLATE_TAG",
    "FORK_DIRECTIVE_PREFIX",
    "SHARE_INSTRUCTION_PREFIX",
    "Message",
    "PrefixStrategyName",
    "SubagentPrefix",
    "build_fork_directive_message",
    "build_share_directive_message",
    "build_subagent_prefix",
    "compute_prefix_hash",
    "is_in_fork_child",
    # P1-8 RunState HITL pause/resume + tool approval
    "HITLController",
    "JsonFileStateStore",
    "PauseReason",
    "RunState",
    "RunStatus",
    "pause_streaming_if_needed",
    # P2-12 background task lifecycle
    "DEFAULT_TASK_TIMEOUT_SECONDS",
    "OnCompleteCallback",
    "Task",
    "TaskManager",
    "TaskState",
]
