/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/studio/slides/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Slides Job
         * @description Register a slide-deck generation job and return its initial status.
         *
         *     Returns immediately (HTTP 202) with state="pending" and a job_id.
         *     The pipeline runs on an asyncio.Task in the background; clients poll
         *     GET /jobs/{id} for state transitions and GET /jobs/{id}/pptx for the
         *     binary once state="done".
         */
        post: operations["create_slides_job_api_studio_slides_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/slides/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Slides Job
         * @description Cheap polling endpoint. Returns the current JobStatus or 404.
         */
        get: operations["get_slides_job_api_studio_slides_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Slides Job
         * @description Cancel an in-flight job. No-op if already terminal.
         */
        delete: operations["cancel_slides_job_api_studio_slides_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/slides/jobs/{job_id}/pptx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Slides Job Pptx
         * @description Stream the rendered .pptx for a completed job.
         *
         *     Returns 404 for unknown/cross-user jobs, 409 if the job is still
         *     running, and 410 if it has been failed/cancelled.
         */
        get: operations["get_slides_job_pptx_api_studio_slides_jobs__job_id__pptx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + readiness gate.
         *
         *     ``revocation_cache.ready`` flips to False if Redis disconnects; the
         *     /health endpoint reports 503 in that window so k8s readiness probes
         *     pull the pod out of the load balancer until it recovers.
         *
         *     jwks_client does not expose ``ready`` directly (it has a fallback
         *     to lazy-fetch on first verify) but its cold-start happens in lifespan
         *     so by the time we serve traffic it has at least one key cached.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * GenerateSpecRequest
         * @description Input to ``/api/studio/slides/generate-spec``.
         */
        GenerateSpecRequest: {
            /** Collection Id */
            collection_id: number;
            /** Extra Instructions */
            extra_instructions?: string | null;
            /** Preset */
            preset: string;
            /**
             * Skip Retrieval
             * @default false
             */
            skip_retrieval: boolean;
            /**
             * Theme Override
             * @description If set, bypasses LLM theme selection and forces this theme. Useful when the user knows the audience better than the LLM. Must be one of THEMES; invalid values rejected by Literal.
             */
            theme_override?: ("corporate_navy" | "academic_paper" | "warm_journal" | "executive_brief" | "startup_pitch") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * JobStatus
         * @description Polling response for a Studio job. Body is JSON, header-buffer-safe.
         */
        JobStatus: {
            /** Created At */
            created_at: string;
            /** Defects */
            defects?: components["schemas"]["VisualDefect"][];
            /** Error */
            error?: string | null;
            /** Job Id */
            job_id: string;
            /**
             * Qa Passes
             * @default 0
             */
            qa_passes: number;
            /** Slide Count */
            slide_count?: number | null;
            /** State */
            state: string;
            /** Step */
            step?: string | null;
            /** Title */
            title?: string | null;
            /** Updated At */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VisualDefect
         * @description One issue spotted by the vision QA pass on a rendered slide.
         */
        VisualDefect: {
            /** Severity */
            severity: string;
            /**
             * Slide Index
             * @description 0-indexed slide that has the defect
             */
            slide_index: number;
            /** Summary */
            summary: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_slides_job_api_studio_slides_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                anila_access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateSpecRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slides_job_api_studio_slides_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                anila_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_slides_job_api_studio_slides_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                anila_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slides_job_pptx_api_studio_slides_jobs__job_id__pptx_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                anila_access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Generated .pptx file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.presentationml.presentation": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
