/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/studio/slides/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Slides Job
         * @description Register a slide-deck generation job and return its initial status.
         *
         *     Returns immediately (HTTP 202) with state="pending" and a job_id.
         *     The pipeline runs on an asyncio.Task in the background; clients poll
         *     GET /jobs/{id} for state transitions and GET /jobs/{id}/pptx for the
         *     binary once state="done".
         */
        post: operations["create_slides_job_api_studio_slides_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/slides/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Slides Job
         * @description Cheap polling endpoint. Returns the current JobStatus or 404.
         *
         *     Read-through: if the in-memory record is gone (studio restarted, or
         *     the job was evicted from the cache) we fall back to the durable job
         *     store so a pre-restart job can still answer status queries.
         */
        get: operations["get_slides_job_api_studio_slides_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Slides Job
         * @description Cancel an in-flight job. No-op if already terminal.
         */
        delete: operations["cancel_slides_job_api_studio_slides_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/studio/slides/jobs/{job_id}/pptx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Slides Job Pptx
         * @description Stream the rendered .pptx for a completed job.
         *
         *     Returns 404 for unknown/cross-user jobs, 409 if the job is still
         *     running, and 410 if it has been failed/cancelled.
         */
        get: operations["get_slides_job_pptx_api_studio_slides_jobs__job_id__pptx_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Report Job
         * @description Register a report generation job and return its initial status.
         *
         *     Returns 202 with state="pending" and a job_id. The pipeline runs in
         *     an asyncio.Task. The client polls GET /jobs/{id} until state="done"
         *     then downloads any of the three formats.
         *
         *     Collection auth is validated synchronously up-front so the user gets
         *     a 403/404 immediately on bad input, not as a delayed "failed" job.
         */
        post: operations["create_report_job_api_reports_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Report Job
         * @description Cheap polling endpoint. Returns the current status or 404.
         *
         *     404 covers both "doesn't exist" and "exists but belongs to someone
         *     else" — never leak cross-user existence. Read-through to the durable
         *     job store when the in-memory record is gone (studio restart / eviction).
         */
        get: operations["get_report_job_api_reports_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Report Job
         * @description Cancel an in-flight report job. No-op if already terminal.
         *
         *     Returns 204 on success or already-terminal; 404 if the job doesn't
         *     belong to the caller (or never existed).
         */
        delete: operations["cancel_report_job_api_reports_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports/jobs/{job_id}/download/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Report
         * @description Stream the rendered artifact for a completed job.
         *
         *     State semantics mirror the slides endpoint:
         *       - 404: unknown id / not yours
         *       - 409: still pending or running
         *       - 410: failed or cancelled
         *       - 200: streams the file from ``{ARTIFACTS_DIR}/{job_id}.{fmt}``
         *
         *     The actual bytes live on disk (reports are too big to keep in-RAM
         *     like the slide pptx_bytes — a typical PDF can hit several MB).
         */
        get: operations["download_report_api_reports_jobs__job_id__download__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mindmaps/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Mindmap Job
         * @description Register a mindmap-generation job and return its initial status.
         *
         *     Returns immediately (HTTP 202) with state="pending" and a job_id.
         *     The pipeline runs on an asyncio.Task in the background; clients poll
         *     GET /jobs/{id} for state transitions and GET /jobs/{id}/download/svg
         *     once state="done".
         */
        post: operations["create_mindmap_job_api_mindmaps_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mindmaps/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Mindmap Job
         * @description Cheap polling endpoint. Returns the current MindmapJobStatus or 404.
         *
         *     Read-through to the durable job store when the in-memory record is
         *     gone (studio restart / eviction).
         */
        get: operations["get_mindmap_job_api_mindmaps_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Mindmap Job
         * @description Cancel an in-flight job. No-op if already terminal.
         */
        delete: operations["cancel_mindmap_job_api_mindmaps_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mindmaps/jobs/{job_id}/download/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Mindmap
         * @description Stream the SVG, DOT source, or spec JSON for a completed job.
         *
         *     ``json`` is the validated MindmapSpec — the SPA's interactive tree
         *     view (expand/collapse + click-to-ask) consumes it instead of the
         *     rendered SVG. Returns 404 for unknown/cross-user jobs, 409 if still
         *     running, and 410 if the job is failed/cancelled.
         */
        get: operations["download_mindmap_api_mindmaps_jobs__job_id__download__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/infographics/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Infographic Job
         * @description Register an infographic-generation job, return 202 immediately.
         */
        post: operations["create_infographic_job_api_infographics_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/infographics/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Infographic Job */
        get: operations["get_infographic_job_api_infographics_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Infographic Job
         * @description Cancel + delete a job, best-effort removing the artifact files.
         */
        delete: operations["delete_infographic_job_api_infographics_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/infographics/jobs/{job_id}/download/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Infographic Artifact
         * @description Stream the HTML or PDF artifact for a completed job.
         *
         *     Returns 404 for unknown/cross-user jobs, 409 if still running,
         *     410 if failed/cancelled, 400 for unknown ``fmt``.
         */
        get: operations["download_infographic_artifact_api_infographics_jobs__job_id__download__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datatables/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Datatable Job
         * @description Register a datatable job and return its initial status.
         *
         *     Authorises the collection access up-front (same pattern as slides)
         *     so the client gets a synchronous 403/404 instead of an opaque
         *     "failed" job seconds later.
         */
        post: operations["create_datatable_job_api_datatables_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datatables/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Datatable Job
         * @description Polling endpoint — returns the current DatatableJobStatus or 404.
         *
         *     Cross-user access returns 404 (NOT 403) so the existence of a job
         *     doesn't leak via status code differentiation. Read-through to the
         *     durable job store when the in-memory record is gone (restart / eviction).
         */
        get: operations["get_datatable_job_api_datatables_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Datatable Job
         * @description Cancel an in-flight datatable job, or delete a terminal one.
         *
         *     Semantics match slides: 204 on success even if the job was already
         *     terminal (frontend deletes its own row regardless). 404 only when
         *     the job doesn't exist or belongs to someone else.
         */
        delete: operations["cancel_datatable_job_api_datatables_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datatables/jobs/{job_id}/download/{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Datatable Artifact
         * @description Serve one of the three exported artifact formats.
         *
         *     fmt ∈ {html, csv, xlsx}.
         *
         *     Status codes:
         *       404 - job missing / not yours / fmt unknown / file gone from disk
         *       409 - job still running (artifacts not yet exported)
         *       410 - job failed or cancelled
         */
        get: operations["download_datatable_artifact_api_datatables_jobs__job_id__download__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + readiness gate.
         *
         *     ``revocation_cache.ready`` flips to False if Redis disconnects; the
         *     /health endpoint reports 503 in that window so k8s readiness probes
         *     pull the pod out of the load balancer until it recovers.
         *
         *     jwks_client does not expose ``ready`` directly (it has a fallback
         *     to lazy-fetch on first verify) but its cold-start happens in lifespan
         *     so by the time we serve traffic it has at least one key cached.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DatatableJobStatus
         * @description Polling response for a datatable job. JSON body — no header buffer issues.
         */
        DatatableJobStatus: {
            /** Job Id */
            job_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled";
            /** Step */
            step?: string | null;
            /** Title */
            title?: string | null;
            preset?: components["schemas"]["DatatablePreset"] | null;
            /** Row Count */
            row_count?: number | null;
            /** Column Count */
            column_count?: number | null;
            /** Error */
            error?: string | null;
            /** Download Urls */
            download_urls?: {
                [key: string]: string;
            } | null;
            /** Artifact Id */
            artifact_id?: string | null;
            /** Classification Level */
            classification_level?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DatatablePreset
         * @description Closed set of datatable presets the LLM picks layout / column-shape from.
         *
         *     String-valued enum so it serialises into JobStatus JSON cleanly and the
         *     frontend can switch on the literal string (no need to mirror Python).
         * @enum {string}
         */
        DatatablePreset: "key_figures" | "entity_attributes" | "timeline_table" | "comparison_table";
        /**
         * GenerateDatatableRequest
         * @description Input to ``POST /api/datatables/jobs``.
         */
        GenerateDatatableRequest: {
            /** Collection Id */
            collection_id: number;
            preset: components["schemas"]["DatatablePreset"];
            /**
             * Seed Query
             * @description Optional retrieval seed. When omitted the runner builds one from `collection.name + preset + extra_instructions`.
             */
            seed_query?: string | null;
            /** Extra Instructions */
            extra_instructions?: string | null;
            /**
             * Document Ids
             * @description Restrict retrieval to these documents only. None = whole collection. Empty list is rejected by csp.
             */
            document_ids?: number[] | null;
            /**
             * Target Columns
             * @description Hints to the LLM about which columns the user wants. Free-form 繁中 strings (e.g. ['品名', '價格', '原產地']). LLM may still add / rename based on chunk content.
             */
            target_columns?: string[] | null;
            /**
             * Top K
             * @default 15
             */
            top_k: number;
            /** Task Id */
            task_id?: string | null;
            /** Source Snapshot Id */
            source_snapshot_id?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * GenerateInfographicRequest
         * @description ``POST /api/infographics/jobs`` 入參。
         *
         *     Mirrors GenerateSpecRequest（slide pipeline）— collection_id 是
         *     csp ingestion collection 的 PK；同一個 user 用同一個 bearer 鑑權。
         */
        GenerateInfographicRequest: {
            /** Collection Id */
            collection_id: number;
            preset: components["schemas"]["InfographicPreset"];
            /** Seed Query */
            seed_query?: string | null;
            /** Extra Instructions */
            extra_instructions?: string | null;
            /** Document Ids */
            document_ids?: number[] | null;
            /**
             * Top K
             * @default 12
             */
            top_k: number;
            /** Task Id */
            task_id?: string | null;
            /** Source Snapshot Id */
            source_snapshot_id?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * GenerateMindmapRequest
         * @description POST body for ``POST /api/mindmaps/jobs``.
         *
         *     All retrieval knobs are bounded (max_depth ≤ 5, top_k ≤ 20) so a
         *     malicious or runaway caller can't force unbounded LLM context. The
         *     defaults (depth=3, k=8) hit the sweet spot we observed in the
         *     Studio slides pipeline: enough chunks for the LLM to write
         *     specifically, not so many the prompt budget blows up.
         */
        GenerateMindmapRequest: {
            /** Collection Id */
            collection_id: number;
            preset: components["schemas"]["MindmapPreset"];
            /** Seed Query */
            seed_query?: string | null;
            /** Extra Instructions */
            extra_instructions?: string | null;
            /** Document Ids */
            document_ids?: number[] | null;
            /**
             * Max Depth
             * @default 3
             */
            max_depth: number;
            /**
             * Top K
             * @default 8
             */
            top_k: number;
            /** Task Id */
            task_id?: string | null;
            /** Source Snapshot Id */
            source_snapshot_id?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * GenerateReportRequest
         * @description POST /api/reports/jobs payload.
         */
        GenerateReportRequest: {
            /** Collection Id */
            collection_id: number;
            preset: components["schemas"]["ReportPreset"];
            /**
             * Extra Instructions
             * @description user-supplied extra hints to flavour the report
             */
            extra_instructions?: string | null;
            /**
             * Document Ids
             * @description optional list to restrict retrieval to specific docs
             */
            document_ids?: number[] | null;
            /**
             * Top K
             * @default 12
             */
            top_k: number;
            /** Task Id */
            task_id?: string | null;
            /** Source Snapshot Id */
            source_snapshot_id?: string | null;
            /** Trace Id */
            trace_id?: string | null;
        };
        /**
         * GenerateSpecRequest
         * @description Input to ``/api/studio/slides/generate-spec``.
         */
        GenerateSpecRequest: {
            /** Collection Id */
            collection_id: number;
            /** Preset */
            preset: string;
            /** Extra Instructions */
            extra_instructions?: string | null;
            /**
             * Skip Retrieval
             * @default false
             */
            skip_retrieval: boolean;
            /** Task Id */
            task_id?: string | null;
            /** Source Snapshot Id */
            source_snapshot_id?: string | null;
            /** Trace Id */
            trace_id?: string | null;
            /**
             * Theme Override
             * @description If set, bypasses LLM theme selection and forces this theme. Useful when the user knows the audience better than the LLM. Must be one of THEMES; invalid values rejected by Literal.
             */
            theme_override?: ("corporate_navy" | "academic_paper" | "warm_journal" | "executive_brief" | "startup_pitch") | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * InfographicJobStatus
         * @description Polling 用 status payload — slide JobStatus 的鏡像版。
         */
        InfographicJobStatus: {
            /** Job Id */
            job_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled";
            /** Step */
            step?: string | null;
            /** Title */
            title?: string | null;
            preset?: components["schemas"]["InfographicPreset"] | null;
            /** Chart Count */
            chart_count?: number | null;
            /** Error */
            error?: string | null;
            /** Download Urls */
            download_urls?: {
                [key: string]: string;
            } | null;
            /** Artifact Id */
            artifact_id?: string | null;
            /** Classification Level */
            classification_level?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * InfographicPreset
         * @description 四個 preset，對應前端 Studio CommandModal 上的快選按鈕。
         *
         *     Renderer 端用 preset 決定要不要展開特定 section（例：timeline_overview
         *     若收到空 timeline，會把 stats grid 拉滿補位）。每個 preset 仍會渲染
         *     所有有資料的 section — preset 只決定 "視覺重心"，不是 hard gate。
         * @enum {string}
         */
        InfographicPreset: "mission_dashboard" | "stats_brief" | "comparison_matrix" | "timeline_overview";
        /**
         * JobStatus
         * @description Polling response for a Studio job. Body is JSON, header-buffer-safe.
         */
        JobStatus: {
            /** Job Id */
            job_id: string;
            /** State */
            state: string;
            /** Step */
            step?: string | null;
            /** Title */
            title?: string | null;
            /** Slide Count */
            slide_count?: number | null;
            /** Defects */
            defects?: components["schemas"]["VisualDefect"][];
            /**
             * Qa Passes
             * @default 0
             */
            qa_passes: number;
            /** Error */
            error?: string | null;
            /** Artifact Id */
            artifact_id?: string | null;
            /** Classification Level */
            classification_level?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * MindmapJobStatus
         * @description Polling response for ``GET /api/mindmaps/jobs/{job_id}``.
         *
         *     Body is JSON, header-buffer-safe. ``download_urls`` is populated on
         *     state=done and keys vary by what got produced — at minimum
         *     ``"svg"``; ``"dot"`` is included for debug downloads (the DOT source
         *     helps users tweak the graph offline).
         */
        MindmapJobStatus: {
            /** Job Id */
            job_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled";
            /** Step */
            step?: string | null;
            /** Title */
            title?: string | null;
            preset?: components["schemas"]["MindmapPreset"] | null;
            /** Node Count */
            node_count?: number | null;
            /** Error */
            error?: string | null;
            /** Download Urls */
            download_urls?: {
                [key: string]: string;
            } | null;
            /** Artifact Id */
            artifact_id?: string | null;
            /** Classification Level */
            classification_level?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MindmapPreset
         * @description The shape of mindmap the user wants.
         *
         *     Values are stable strings — the renderer's preset → fill-colour
         *     mapping and the LLM system prompt's "shape hint" both switch on
         *     these values, so changing them is a breaking change.
         * @enum {string}
         */
        MindmapPreset: "concept_tree" | "task_breakdown" | "sop_flow" | "org_relationships";
        /**
         * ReportJobStatus
         * @description Response shape for POST /jobs (202) and GET /jobs/{id}.
         *
         *     Mirrors ``app.schemas.studio.JobStatus`` but with report-specific
         *     fields (preset, sections_count, references_count, download_urls).
         *     Slide-specific fields (defects, qa_passes, slide_count) are not here.
         */
        ReportJobStatus: {
            /** Job Id */
            job_id: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "done" | "failed" | "cancelled";
            /** Step */
            step?: string | null;
            /** Title */
            title?: string | null;
            preset?: components["schemas"]["ReportPreset"] | null;
            /** References Count */
            references_count?: number | null;
            /** Sections Count */
            sections_count?: number | null;
            /** Error */
            error?: string | null;
            /**
             * Download Urls
             * @description {'html': ..., 'pdf': ..., 'docx': ...} — relative API paths, not absolute URLs. Frontend axios prepends its base URL.
             */
            download_urls?: {
                [key: string]: string;
            } | null;
            /** Artifact Id */
            artifact_id?: string | null;
            /** Classification Level */
            classification_level?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ReportPreset
         * @description The 4 supported report presets.
         *
         *     Each preset maps to:
         *     - a Jinja2 template variant (different typography / colour / spacing),
         *     - a different LLM prompt voice (formal academic / executive / tutorial /
         *       enterprise),
         *     - a different default section structure hint.
         *
         *     Adding a new preset is a 3-line change: add the enum, add the template,
         *     add the prompt voice in ``report_runner``.
         * @enum {string}
         */
        ReportPreset: "deep_tech_review" | "key_summary" | "teaching_handout" | "external_comms";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VisualDefect
         * @description One issue spotted by the vision QA pass on a rendered slide.
         */
        VisualDefect: {
            /**
             * Slide Index
             * @description 0-indexed slide that has the defect
             */
            slide_index: number;
            /** Severity */
            severity: string;
            /** Summary */
            summary: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_slides_job_api_studio_slides_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateSpecRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slides_job_api_studio_slides_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_slides_job_api_studio_slides_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_slides_job_pptx_api_studio_slides_jobs__job_id__pptx_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Generated .pptx file */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.openxmlformats-officedocument.presentationml.presentation": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_job_api_reports_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_job_api_reports_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_report_job_api_reports_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_report_api_reports_jobs__job_id__download__fmt__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
                fmt: "html" | "pdf" | "docx";
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/html; charset=utf-8": unknown;
                    "application/pdf": unknown;
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_mindmap_job_api_mindmaps_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateMindmapRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MindmapJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_mindmap_job_api_mindmaps_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MindmapJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_mindmap_job_api_mindmaps_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_mindmap_api_mindmaps_jobs__job_id__download__fmt__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
                fmt: "svg" | "dot" | "json";
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Generated mindmap (SVG primary, DOT for debug, JSON spec for the interactive tree view) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "image/svg+xml": unknown;
                    "text/vnd.graphviz": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_infographic_job_api_infographics_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateInfographicRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfographicJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_infographic_job_api_infographics_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfographicJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_infographic_job_api_infographics_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_infographic_artifact_api_infographics_jobs__job_id__download__fmt__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
                fmt: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_datatable_job_api_datatables_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateDatatableRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatatableJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_datatable_job_api_datatables_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatatableJobStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_datatable_job_api_datatables_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_datatable_artifact_api_datatables_jobs__job_id__download__fmt__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                job_id: string;
                fmt: string;
            };
            cookie?: {
                "__Host-anila_access_token"?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
