"""Shared tree/profile fixtures for the agent download bundle tests.

Builds throwaway scaffold / wheelhouse / profile / CA trees so the tests read
a real zip instead of asserting on source files. Kept out of ``conftest.py``
because only the two download test modules need it.
"""
from __future__ import annotations

import datetime as _dt
import hashlib
import json
import zipfile
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

# Deliberately split across two modules and two tags: the quickstart scaffold
# must pin these, and the wheelhouse must match them exactly.
REQUIREMENTS_IN = "fastapi==1.2.3\ncryptography==2.0.0\n"
AGENT_NAME_DEFAULT = "quickstart-demo"

AGENT_PY = '''from collections.abc import AsyncIterator

AGENT_NAME = "quickstart-demo"  # ← 下載預填；五分鐘路徑不改。註冊名不可變

COLLECTION_ID: int | None = None  # ← 選填：已綁定的資料來源，無則不改


async def respond(messages, context, llm) -> AsyncIterator[str]:
    yield "ok"
'''

SCAFFOLD_FILE_BODIES = {
    "server.py": "SERVER = True\n",
    "platform_io.py": "PLATFORM = True\n",
    "llm.py": "LLM = True\n",
    "Dockerfile": "FROM python:3.13-slim\n",
    "compose.yaml": "services:\n  agent:\n    build: .\n",
    ".gitignore": ".env\n__pycache__/\n",
    "README.md": "# quickstart\n",
    "LICENSE": "Apache-2.0\n",
    "run.sh": "#!/bin/bash\n# fixture\n",
    "IMAGE_VERSION": "1\n",
}


def sha256_bytes(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def make_ca_pem(path: Path) -> Path:
    """Write a real, parseable public chain; return the path.

    Returns the *path* (not bytes) because that is what a profile stores —
    ``str(some_bytes)`` is not a usable file path, and mixing the two silently
    yields "CA not found".
    """
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, "ANILA Test CA")])
    now = _dt.datetime(2026, 1, 1, tzinfo=_dt.timezone.utc)
    cert = (
        x509.CertificateBuilder()
        .subject_name(name)
        .issuer_name(name)
        .public_key(key.public_key())
        .serial_number(1234)
        .not_valid_before(now)
        .not_valid_after(now + _dt.timedelta(days=3650))
        .sign(key, hashes.SHA256())
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))
    return path


def make_wheel(
    directory: Path,
    dist: str,
    version: str,
    *,
    pytag: str = "py3",
    abitag: str = "none",
    plattag: str = "any",
) -> tuple[Path, str]:
    """Write a minimal but structurally valid wheel; return ``(path, sha256)``."""
    directory.mkdir(parents=True, exist_ok=True)
    filename = f"{dist}-{version}-{pytag}-{abitag}-{plattag}.whl"
    path = directory / filename
    metadata = f"Metadata-Version: 2.1\nName: {dist}\nVersion: {version}\n"
    with zipfile.ZipFile(path, "w") as zf:
        zf.writestr(f"{dist}-{version}.dist-info/METADATA", metadata)
    return path, sha256_bytes(path.read_bytes())


def make_wheelhouse(directory: Path, *, include_cp313: bool = True) -> str:
    """Create the verified wheelhouse and return the matching lock text."""
    _, fastapi_hash = make_wheel(directory, "fastapi", "1.2.3")
    _, crypto_hash = make_wheel(
        directory,
        "cryptography",
        "2.0.0",
        pytag="cp313.cp313" if include_cp313 else "py3.cp313.abi3",
        abitag="cp313" if include_cp313 else "none",
        plattag="manylinux_2_17_x86_64" if include_cp313 else "any",
    )
    return (
        "# autogenerated by pip-compile\n"
        f"fastapi==1.2.3 \\\n    --hash=sha256:{fastapi_hash}\n"
        f"cryptography==2.0.0 \\\n    --hash=sha256:{crypto_hash}\n"
    )


def build_scaffold(
    root: Path,
    *,
    lock_text: str,
    agent_py: str = AGENT_PY,
) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    (root / "agent.py").write_text(agent_py, encoding="utf-8")
    (root / "requirements.in").write_text(REQUIREMENTS_IN, encoding="utf-8")
    (root / "requirements.lock").write_text(lock_text, encoding="utf-8")
    for name, body in SCAFFOLD_FILE_BODIES.items():
        (root / name).write_text(body, encoding="utf-8")
    return root


def build_profile(
    path: Path,
    *,
    ca_path: Path | None,
    model_keys: tuple[str, ...] = ("7", "demo-model"),
    default_model_key: str | None = "7",
    csp_base_url: str = "https://anila.test",
    **extra: object,
) -> Path:
    payload: dict[str, object] = {
        "csp_base_url": csp_base_url,
        "models": {
            key: {
                "llm_base_url": f"https://llm.test/{key}/v1",
                "llm_model": f"ncsist/{key}",
                "auth_required": True,
            }
            for key in model_keys
        },
    }
    if ca_path is not None:
        payload["csp_ca_file"] = str(ca_path)
    if default_model_key is not None:
        # A default pointing at a model this call did not create would make the
        # profile self-inconsistent; drop it instead of shipping a broken one.
        if default_model_key in model_keys:
            payload["default_model_key"] = default_model_key
    payload.update(extra)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")
    return path


def build_all_inputs(tmp_path: Path) -> dict[str, Path]:
    """One call that produces every input the quickstart builder needs."""
    ca_path = make_ca_pem(tmp_path / "profile" / "ca.pem")
    ca_bytes = ca_path.read_bytes()
    lock_text = make_wheelhouse(tmp_path / "wheels")
    scaffold = build_scaffold(tmp_path / "quickstart", lock_text=lock_text)
    profile = build_profile(tmp_path / "profile" / "site.json", ca_path=ca_path)
    advanced = tmp_path / "advanced"
    advanced.mkdir(parents=True, exist_ok=True)
    (advanced / "pyproject.toml").write_text(
        '[project]\nname = "anila-agent"\nversion = "1.0.0"\n', encoding="utf-8"
    )
    (advanced / "README.md").write_text("# advanced\n", encoding="utf-8")
    (advanced / "anila_agent").mkdir(exist_ok=True)
    (advanced / "anila_agent" / "__init__.py").write_text("", encoding="utf-8")
    (advanced / ".env.example").write_text("X=1\n", encoding="utf-8")
    (advanced / ".env").write_text("SECRET=real\n", encoding="utf-8")
    (advanced / "private.key").write_text("KEY\n", encoding="utf-8")
    (advanced / "__pycache__").mkdir(exist_ok=True)
    (advanced / "__pycache__" / "x.pyc").write_text("", encoding="utf-8")
    return {
        "scaffold": scaffold,
        "wheels": tmp_path / "wheels",
        "profile": profile,
        "ca": ca_path,
        "advanced": advanced,
        "ca_bytes": ca_bytes,
    }
