"""Password hashing compatibility tests."""

import pytest

from app.utils.security import hash_password, verify_password


# Generated by the pre-change passlib[bcrypt] code path with cost 12.
LEGACY_PASSLIB_BCRYPT_HASH = "$2b$12$Chzl3YRRv.pMg5VKcDmXW.68qjZiFmc9TBUEXHqB/X9X54H6mY6om"
LEGACY_PASSWORD = "fixture-legacy-password"


def test_verifies_hash_written_by_legacy_passlib() -> None:
    assert verify_password(LEGACY_PASSWORD, LEGACY_PASSLIB_BCRYPT_HASH)
    assert not verify_password(
        "fixture-wrong-password",
        LEGACY_PASSLIB_BCRYPT_HASH,
    )
    assert not verify_password("", LEGACY_PASSLIB_BCRYPT_HASH)


def test_hashing_keeps_bcrypt_format_and_cost() -> None:
    hashed = hash_password("fixture-new-password")
    scheme, version, cost, salt_and_checksum = hashed.split("$")

    assert scheme == ""
    assert version == "2b"
    assert cost == "12"
    assert len(salt_and_checksum) == 53
    assert verify_password("fixture-new-password", hashed)


def test_none_handling_matches_legacy_wrapper() -> None:
    with pytest.raises(TypeError):
        hash_password(None)  # type: ignore[arg-type]
    with pytest.raises(TypeError):
        verify_password(None, LEGACY_PASSLIB_BCRYPT_HASH)  # type: ignore[arg-type]
