"""Password hashing compatibility tests."""

import pytest

from app.utils.security import hash_password, verify_password


LEGACY_OVERLONG_PASSWORD = "fake-legacy-overlength-" + "x" * 60
LEGACY_PASSLIB_OVERLONG_HASH = "$2b$12$GLkZO34KEf0xngzFpCe5X.WLJGyDI/RD5bw.IAa32LezvBldid7ae"
LEGACY_BARE_BCRYPT_PASSWORD = "FakeLegacyBarePrefix!123"
LEGACY_BARE_BCRYPT_HASH = "$2$12$2bCOQitoAIFTNEMzyEssfu.hWjorcG0S5YF6fwmzre/j4y9wJJCzC"


# Generated by the pre-change passlib[bcrypt] code path with cost 12.
LEGACY_PASSLIB_BCRYPT_HASH = "$2b$12$Chzl3YRRv.pMg5VKcDmXW.68qjZiFmc9TBUEXHqB/X9X54H6mY6om"
LEGACY_PASSWORD = "fixture-legacy-password"


def test_verifies_hash_written_by_legacy_passlib() -> None:
    assert verify_password(LEGACY_PASSWORD, LEGACY_PASSLIB_BCRYPT_HASH)
    assert not verify_password(
        "fixture-wrong-password",
        LEGACY_PASSLIB_BCRYPT_HASH,
    )
    assert not verify_password("", LEGACY_PASSLIB_BCRYPT_HASH)


def test_hashing_keeps_bcrypt_format_and_cost() -> None:
    hashed = hash_password("fixture-new-password")
    scheme, version, cost, salt_and_checksum = hashed.split("$")

    assert scheme == ""
    assert version == "2b"
    assert cost == "12"
    assert len(salt_and_checksum) == 53
    assert verify_password("fixture-new-password", hashed)


def test_passwords_preserve_historical_72_byte_truncation() -> None:
    cases = (
        ("ascii-72", "A" * 72, "A" * 72),
        ("ascii-73", "A" * 73, "A" * 72),
        ("cjk-75-bytes", "你" * 25, "你" * 24),
    )
    for label, password, truncated_password in cases:
        hashed = hash_password(password)
        assert verify_password(password, hashed), label
        assert verify_password(truncated_password, hashed), label


def test_old_passlib_overlong_hash_still_verifies() -> None:
    assert verify_password(LEGACY_OVERLONG_PASSWORD, LEGACY_PASSLIB_OVERLONG_HASH)
    assert verify_password(
        LEGACY_OVERLONG_PASSWORD[:72],
        LEGACY_PASSLIB_OVERLONG_HASH,
    )


def test_nul_bytes_are_accepted_without_nul_termination() -> None:
    first = "fake-nul-prefix" + chr(0) + "suffix-one"
    second = "fake-nul-prefix" + chr(0) + "suffix-two"
    hashed = hash_password(first)

    assert verify_password(first, hashed)
    assert not verify_password(second, hashed)


def test_bare_bcrypt_prefix_is_rejected_fail_closed() -> None:
    assert not verify_password(
        LEGACY_BARE_BCRYPT_PASSWORD,
        LEGACY_BARE_BCRYPT_HASH,
    )


def test_none_handling_matches_legacy_wrapper() -> None:
    with pytest.raises(TypeError):
        hash_password(None)  # type: ignore[arg-type]
    with pytest.raises(TypeError):
        verify_password(None, LEGACY_PASSLIB_BCRYPT_HASH)  # type: ignore[arg-type]
    assert verify_password(LEGACY_PASSWORD, None) is False  # type: ignore[arg-type]
