"""Security primitives shared across ANILA services.

The package deliberately has no dependency on CSP, anila-core, a database
schema, or a web framework.  Service layers translate these primitives into
their own HTTP and persistence contracts.
"""

from anila_security.credential_crypto import (
    decrypt_credential,
    encrypt_credential,
    legacy_fallback_count,
    reset_legacy_fallback_count,
)
from anila_security.url_guard import (
    ENDPOINT_KIND_AGENT,
    ENDPOINT_KIND_GENERIC,
    ENDPOINT_KIND_MODEL,
    FIXABLE_BY_TRUST_HOST,
    REASON_DENY_HOST,
    REASON_EMPTY,
    REASON_INTERNAL_ZONE,
    REASON_NO_HOSTNAME,
    REASON_PRIVATE_IP,
    REASON_SCHEME,
    REASON_SINGLE_LABEL,
    REASON_UNSAFE_IP,
    UnsafeEndpointError,
    clear_trusted_host_providers,
    register_trusted_host_provider,
    validate_outbound_url,
)
from anila_security.pilot_profile import (
    PilotTarget,
    PilotProfileError,
    VerifiedPilotAdmission,
    verify_signed_pilot_profile,
)
from anila_security.model_governance import (
    CLASSIFICATION_LEVELS,
    CLASSIFICATION_ORDER,
    GATEWAY_ID,
    GOVERNANCE_INVENTORY_SCHEMA,
    GOVERNANCE_PROFILE_SCHEMA,
    INFERENCE_SCANNER_EXCLUDED_PATH_PARTS,
    INFERENCE_SCANNER_PATTERN_VERSION,
    INFERENCE_SCANNER_SCHEMA,
    INFERENCE_SCANNER_SOURCE_ROOTS,
    REQUIRED_APPROVER_ROLES,
    CallsiteBinding,
    Deployment,
    InferenceCallsite,
    ModelArtifact,
    ModelGovernanceAuthorization,
    ModelGovernanceError,
    VerifiedModelGovernanceAuthority,
    canonical_json,
    classification_rank,
    inventory_content_sha256,
    parse_classification_level,
    parse_rfc3339,
    profile_content_sha256,
    require_identifier,
    require_hex_sha256,
    require_sha256,
    sha256_hex,
    validate_inventory_payload,
    validate_profile_shape,
    validate_profile_approver_shape,
    verify_profile_signatures,
)
from anila_security.queue_integrity import create_queue_proof, verify_queue_proof

__all__ = [
    "ENDPOINT_KIND_AGENT",
    "ENDPOINT_KIND_GENERIC",
    "ENDPOINT_KIND_MODEL",
    "FIXABLE_BY_TRUST_HOST",
    "REASON_DENY_HOST",
    "REASON_EMPTY",
    "REASON_INTERNAL_ZONE",
    "REASON_NO_HOSTNAME",
    "REASON_PRIVATE_IP",
    "REASON_SCHEME",
    "REASON_SINGLE_LABEL",
    "REASON_UNSAFE_IP",
    "UnsafeEndpointError",
    "PilotProfileError",
    "PilotTarget",
    "VerifiedPilotAdmission",
    "clear_trusted_host_providers",
    "create_queue_proof",
    "decrypt_credential",
    "encrypt_credential",
    "legacy_fallback_count",
    "register_trusted_host_provider",
    "reset_legacy_fallback_count",
    "validate_outbound_url",
    "verify_signed_pilot_profile",
    "verify_queue_proof",
    "CLASSIFICATION_LEVELS",
    "CLASSIFICATION_ORDER",
    "CallsiteBinding",
    "GATEWAY_ID",
    "GOVERNANCE_INVENTORY_SCHEMA",
    "GOVERNANCE_PROFILE_SCHEMA",
    "INFERENCE_SCANNER_EXCLUDED_PATH_PARTS",
    "INFERENCE_SCANNER_PATTERN_VERSION",
    "INFERENCE_SCANNER_SCHEMA",
    "INFERENCE_SCANNER_SOURCE_ROOTS",
    "REQUIRED_APPROVER_ROLES",
    "Deployment",
    "InferenceCallsite",
    "ModelArtifact",
    "ModelGovernanceAuthorization",
    "ModelGovernanceError",
    "VerifiedModelGovernanceAuthority",
    "canonical_json",
    "classification_rank",
    "inventory_content_sha256",
    "parse_classification_level",
    "parse_rfc3339",
    "profile_content_sha256",
    "require_identifier",
    "require_hex_sha256",
    "require_sha256",
    "sha256_hex",
    "validate_inventory_payload",
    "validate_profile_shape",
    "validate_profile_approver_shape",
    "verify_profile_signatures",
]
