backend: "python"
max_batch_size: 0
input [
    {
        name: "query"
        data_type: TYPE_STRING
        optional: true
        dims: [ 1 ]
    },
    {
        name: "documents"
        data_type: TYPE_STRING
        optional: true
        dims: [ 1, -1 ]
    }
]
output [
    {
        name: "embeddings"
        data_type: TYPE_FP32
        dims: [ 1, -1 ]
    }
]

parameters {
    key: "model_path"
    value: {
        string_value: "/workspace/model/NV-Embed-v2"
    }
}
parameters {
    key: "device"
    value: {
        string_value: "cuda:0"
    }
}

instance_group [
    {
        count: 1
        kind: KIND_CPU
    }
]