apiVersion: v2
name: onyx
description: A Helm chart for Kubernetes
home: https://www.onyx.app/
sources:
  - "https://github.com/onyx-dot-app/onyx"
type: application
version: 0.4.46
appVersion: latest
annotations:
  category: Productivity
  licenses: MIT
  images: |
    - name: webserver
      image: docker.io/onyxdotapp/onyx-web-server:latest
    - name: background
      image: docker.io/onyxdotapp/onyx-backend:latest
    - name: vespa
      image: vespaengine/vespa:8.609.39
dependencies:
  - name: cloudnative-pg
    version: 0.26.0
    repository: https://cloudnative-pg.github.io/charts
    condition: postgresql.enabled
    alias: postgresql
  - name: vespa
    version: 0.2.25
    repository: https://onyx-dot-app.github.io/vespa-helm-charts
    condition: vespa.enabled
  - name: opensearch
    version: 3.4.0
    repository: https://opensearch-project.github.io/helm-charts
    condition: opensearch.enabled
  - name: ingress-nginx
    version: 4.13.3
    repository: https://kubernetes.github.io/ingress-nginx
    condition: nginx.enabled
    alias: nginx
  - name: redis
    version: 0.16.6
    repository: https://ot-container-kit.github.io/helm-charts
    condition: redis.enabled
  - name: minio
    version: 5.4.0
    repository: https://charts.min.io/
    condition: minio.enabled
  - name: code-interpreter
    version: 0.3.3
    repository: https://onyx-dot-app.github.io/python-sandbox/
    condition: codeInterpreter.enabled
